############################# English ############################
[en]
languageName = "En"
title = "CloudNod"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
# copyright
copyright = "Design By [CloudNod](https://CloudNod.dev/) Develop By [CloudNod](https://CloudNod.dev/)"

